apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-website-chart.fullname" . }}
  labels:
    {{- include "nginx-website-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-website-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-website-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - name: website-content
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: website-content
        configMap:
          name: {{ include "nginx-website-chart.fullname" . }}-website
