apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-website-chart.fullname" . }}
  labels:
    {{- include "nginx-website-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-website-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-website-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - name: website-content
          mountPath: /usr/share/nginx/html
          readOnly: true
        {{- if .Values.nginx.config }}
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: website-content
        configMap:
          name: {{ include "nginx-website-chart.fullname" . }}-website
      {{- if .Values.nginx.config }}
      - name: nginx-config
        configMap:
          name: {{ include "nginx-website-chart.fullname" . }}-nginx-config
      {{- end }}
