{{- if .Values.nginx.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-website-chart.fullname" . }}-nginx-config
  labels:
    {{- include "nginx-website-chart.labels" . | nindent 4 }}
data:
  default.conf: |
{{ .Values.nginx.config | indent 4 }}
{{- end }}