apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-website-chart.fullname" . }}
  labels:
    {{- include "nginx-website-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  selector:
    {{- include "nginx-website-chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    {{- if .Values.service.httpsPort }}
    - port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: https
    {{- end }}
      